name: Deploy

on:
  push:
    branches: [main]

env:
  ACTIONS_CI: "is_in_github"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install packages
        run: pip install pylint flask flask_sqlalchemy pytest pytest-dotenv python-dotenv psycopg2 pandas
      - name: Set environment value (same as export locally)
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > $GITHUB_ENV
      - name: Run Python unit tests
        run: python3 -m pytest
      - name: Run Lint
        run: pylint --fail-under 7.0 main
      - name: Deploy to cPouta
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            source script.sh
            cd movie-book-backend
            git pull
            source ../killscript.sh
      - name: Install coverage reporting
        run: pip install coverage
      - name: Conduct coverage reporting
        run: coverage run --branch -m pytest main
      - name: Show coverage report
        run: coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
