name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install packages
        run: pip install pylint flask flask_sqlalchemy pytest pytest-dotenv python-dotenv psycopg2
      - name: Create .env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
      - name: Run Python unit tests
        run: python3 -m pytest
      - name: Deploy to cPouta
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            source script.sh
            cd movie-book-backend
            touch .env
            echo DATABASE_URL=${{ secrets.DATABASE_LOCAL_URL }} > .env
            git pull
            source ../killscript.sh
